[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.40", default-features = false, features = ["noise"] }
rand = "0.8.5"
thiserror = "1.0"
argon2 = "0.5"
chacha20poly1305 = { version = "0.10", features = ["alloc"] }
